### ISSUE TITLE
Chat/Messaging

### ISSUE THREAD

**Issue by mathis1337** [ReserveBlockIO/ReserveBlock-Core#104]

**Comment by mathis1337** [comment]
Ability for wallet to send messages. No specific method or standard. Open to community feedback.

**Comment by wildcommunist** [comment]
What kind of messages? As in simple text exchange?

**Comment by mathis1337** [comment]
Yes. For p2p auctions it might be relevant for users to be able to communicate. This would be done p2p but not on chain as that would be way too much data burden.

**Comment by mathis1337** [comment]
This is done is p2p auction within the DST.
