### ISSUE TITLE
Add validation status to CLI app main menu

### ISSUE THREAD

**Issue by wildcommunist** [ReserveBlockIO/ReserveBlock-Core#145]
**Is your feature request related to a problem? Please describe.**
Since running many validating nodes for RB, and working only through CLI app on linux, it would be super fantastic to have a simple overview wether the node is valdiating correctly.

**Describe the solution you'd like**
A simple way to do this, would be to add validation summary to the CLI main menu.
![image](https://user-images.githubusercontent.com/96243054/217161034-a28eb407-7687-406a-84a0-704fc7361706.png)
under time and update status would be ideal.

**Describe alternatives you've considered**
Checking the node logs or the `/api/V1/IsValidating` is not practical when u have > 10 nodes running.

**Comment by mathis1337** [comment]
There is now a basic CLI output to help with containerized nodes. 

please by the arg `basic` and it will keep CLI simple and display validator info

Can be seen in commit: 5580464cdcd93d01580df7107d4c112108d5b0d3

example:
![image](https://user-images.githubusercontent.com/20599614/217360532-ddd0bc22-6c97-4bba-87f4-aecd5ac6f283.png)
