### ISSUE TITLE
Validator registration via the CLI

### ISSUE THREAD

**Issue by wildcommunist** [ReserveBlockIO/ReserveBlock-Core#146]
**Is your feature request related to a problem? Please describe.**
In order to become a validator on the network, few manual steps (either via the API or CLI) have to be performed.
1) Import key into the wallet
2) Activate master node
3) Now the cli app can be started with `privKey` arg and start validating without having to start master node again

**Describe the solution you'd like**
It would be fantastic to eliminate the manu work and have the cli import the private key and activate the master node. In order for the cli to do that the `config.txt` params for `ValidatorAddress` and `ValidatorName` as well as `privKey` arg need to be set

**Describe alternatives you've considered**
An alternative is the API but when node management is in the 10s or 100s thats a lot of manual labour

**Comment by mathis1337** [comment]
This has been addressed in commit : 5580464cdcd93d01580df7107d4c112108d5b0d3

you can now startup a validator with the following args

privKey=someprivekey start-validator validator-name=somevalnamenospaces

it is ok to leave this after the fact as it will just skip over once validator is detected, so no need to modify the args. This will also auto start the validator for you.
