### ISSUE TITLE
Separate Blockchain/Snapshot database files from Wallets files

### ISSUE THREAD

**Issue by alexx-ftw** [ReserveBlockIO/ReserveBlock-Core#151]
**Is your feature request related to a problem? Please describe.**
Every time it is required to import a new Snapshot or for some reason the database gets corrupted, it is needed to add all of the wallets again using their private keys, which is really tedious.

**Describe the solution you'd like**
Separate those two functionalities so that it is possible to import a snapshot or even start from block 0, without having to re-add all wallets.

**Describe alternatives you've considered**
Have two different folders, one for Wallets, and another for the Databases.

**Comment by mathis1337** [comment]
This is how snapshots work. The reason being that the wallet file will contain transactions. If you want to start from block 0 you simply just don't use a snapshot. Snapshots in order to work must start with a fresh instance. If this is not suitable then simply don't use and you can sync from 0.

**Comment by mathis1337** [comment]
Also just to add the wallet files are separated from a snapshot but they are not agnostic nor should they be.
