### ISSUE TITLE
Prevent tx submission (or issue a warning) when node has 0 peers

### ISSUE THREAD

**Issue by wildcommunist** [ReserveBlockIO/ReserveBlock-Core#157]
**Is your feature request related to a problem? Please describe.**
When submitting a TX to a node via the API that is stalled (block rejection or any other reason that prevent block progression), transaction is accepted but obviously is not broadcasted.

**Describe the solution you'd like**
Reject the transaction outright or issue a warning that there are no peers and the TX will not be broadcast.

**Describe alternatives you've considered**
Forming transaction manually via external tools (that takes time to get right)

**Comment by mathis1337** [comment]
This is already a thing. Anytime `SendTXMempool` method is called there is a peerConnected Check. 
```
var peersConnected = await ArePeersConnected();

            if (!peersConnected)
            {
                //Need peers
                Console.WriteLine("Failed to broadcast Transaction. No peers are connected to you.");
                LogUtility.Log("TX failed. No Peers: " + txSend.Hash, "P2PClient.SendTXMempool()");
            }
```

So if no peers are connected it does not go through, however, it is helpful to user to see a failed TX appear so they know this. It doesn't really harm anything for it to be there. If/When you reconnect to peers the TX also has the potential to be rebroadcasted. If not it goes stale within 60 minutes I believe.

**Comment by wildcommunist** [comment]
The only reason i noticed the the transaction did not go through when using the API was that i got an instant reply from the API 

` Success! TxId: 85f9653c07183741020c2b79b075039282acbc37f8beca85dae93ed1450d2828`

I had to send about 80 transactions and they were processed in under 10 seconds, which was unusual. I think the API need to return an error also. There is shouldn't be anything implicit. I am a strong believer of being explicit

**Comment by mathis1337** [comment]
ok thank you. I will look into code to provide further detail.

**Comment by mathis1337** [comment]
The wallet was updated to store a TX, so when peers do become available it will broadcast out. This is relevant for offline tx creation/submission
