### ISSUE TITLE
Sometimes reconnect to validator will result in answers not being sent

### ISSUE THREAD

**Issue by TrilliumSEN** [ReserveBlockIO/ReserveBlock-Core#8]
Sometimes on validator pool reconnect answers will stop at the time of the reconnect, but will continue to receive answer response, just won't send a question beyond that initial loss point.

**Comment by mathis1337** [comment]
Advanced logging was added to determine the root cause of this. Will revisit once new information is gathered.

**Comment by mathis1337** [comment]
Logging not reporting any issues. will monitor. Closing for now.
